import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
import { useMoralis } from "react-moralis";

const FujiSupportedChain = ["43113"] 
const SepoliaSupportedChain = ["11155111"]

const supportedChains = [...FujiSupportedChain, ...SepoliaSupportedChain];
export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>Web3 Raffle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head>
      <Header />
      {isWeb3Enabled ? (
        <div>
          {supportedChains.includes(parseInt(chainId).toString()) ? (
            <div className="flex flex-row">
              <LotteryEntrance className="p-8" />
            </div>
          ) : (
            <div className="text-[#ffaaf] text-center font-bold  py-4 px-4  text-2xl">
                        <br /> {`Please switch to a supported chain !`} <br />
               The supported chains  are Avalanche Testnet & Sepolia ETH : <br /> 
                 Id {FujiSupportedChain.join(",")} and  Id {SepoliaSupportedChain.join(",")}
                  </div> 
          )}
        </div>
      ) : (
          <div> </div> 
      )}
      </div>
      );   
      
    

}
